In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns 

In [2]:
df=pd.read_csv("F:\DataTrained project datasets\project dynamic m20/Skyserver.csv")

In [3]:
df.head()

objid          ra       dec         u         g         r         i  \
0  1.237650e+18  183.531326  0.089693  19.47406  17.04240  15.94699  15.50342   
1  1.237650e+18  183.598371  0.135285  18.66280  17.21449  16.67637  16.48922   
2  1.237650e+18  183.680207  0.126185  19.38298  18.19169  17.47428  17.08732   
3  1.237650e+18  183.870529  0.049911  17.76536  16.60272  16.16116  15.98233   
4  1.237650e+18  183.883288  0.102557  17.55025  16.26342  16.43869  16.55492   

          z  run  rerun  camcol  field     specobjid   class  redshift  plate  \
0  15.22531  752    301       4    267  3.722360e+18    STAR -0.000009   3306   
1  16.39150  752    301       4    267  3.638140e+17    STAR -0.000055    323   
2  16.80125  752    301       4    268  3.232740e+17  GALAXY  0.123111    287   
3  15.90438  752    301       4    269  3.722370e+18    STAR -0.000111   3306   
4  16.61326  752    301       4    269  3.722370e+18    STAR  0.000590   3306   

     mjd  fiberid  
0  54922      491  
1  51615      541  
2  52023      513  
3  54922      510  
4  54922      512

In [4]:
df.shape

(10000, 18)

In [5]:
df.columns

Index(['objid', 'ra', 'dec', 'u', 'g', 'r', 'i', 'z', 'run', 'rerun', 'camcol',
       'field', 'specobjid', 'class', 'redshift', 'plate', 'mjd', 'fiberid'],
      dtype='object')

In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le=LabelEncoder()

In [10]:
df["class"]=le.fit_transform(df["class"])

In [11]:
df.head()

objid          ra       dec         u         g         r         i  \
0  1.237650e+18  183.531326  0.089693  19.47406  17.04240  15.94699  15.50342   
1  1.237650e+18  183.598371  0.135285  18.66280  17.21449  16.67637  16.48922   
2  1.237650e+18  183.680207  0.126185  19.38298  18.19169  17.47428  17.08732   
3  1.237650e+18  183.870529  0.049911  17.76536  16.60272  16.16116  15.98233   
4  1.237650e+18  183.883288  0.102557  17.55025  16.26342  16.43869  16.55492   

          z  run  rerun  camcol  field     specobjid  class  redshift  plate  \
0  15.22531  752    301       4    267  3.722360e+18      2 -0.000009   3306   
1  16.39150  752    301       4    267  3.638140e+17      2 -0.000055    323   
2  16.80125  752    301       4    268  3.232740e+17      0  0.123111    287   
3  15.90438  752    301       4    269  3.722370e+18      2 -0.000111   3306   
4  16.61326  752    301       4    269  3.722370e+18      2  0.000590   3306   

     mjd  fiberid  
0  54922      491  
1  51615      541  
2  52023      513  
3  54922      510  
4  54922      512

In [12]:
df.describe()

objid            ra           dec             u             g  \
count  1.000000e+04  10000.000000  10000.000000  10000.000000  10000.000000   
mean   1.237650e+18    175.529987     14.836148     18.619355     17.371931   
std    1.577039e+05     47.783439     25.212207      0.828656      0.945457   
min    1.237650e+18      8.235100     -5.382632     12.988970     12.799550   
25%    1.237650e+18    157.370946     -0.539035     18.178035     16.815100   
50%    1.237650e+18    180.394514      0.404166     18.853095     17.495135   
75%    1.237650e+18    201.547279     35.649397     19.259232     18.010145   
max    1.237650e+18    260.884382     68.542265     19.599900     19.918970   

                  r             i             z           run    rerun  \
count  10000.000000  10000.000000  10000.000000  10000.000000  10000.0   
mean      16.840963     16.583579     16.422833    981.034800    301.0   
std        1.067764      1.141805      1.203188    273.305024      0.0   
min       12.431600     11.947210     11.610410    308.000000    301.0   
25%       16.173333     15.853705     15.618285    752.000000    301.0   
50%       16.858770     16.554985     16.389945    756.000000    301.0   
75%       17.512675     17.258550     17.141447   1331.000000    301.0   
max       24.802040     28.179630     22.833060   1412.000000    301.0   

             camcol         field     specobjid         class      redshift  \
count  10000.000000  10000.000000  1.000000e+04  10000.000000  10000.000000   
mean       3.648700    302.380100  1.645022e+18      0.915400      0.143726   
std        1.666183    162.577763  2.013998e+18      0.952856      0.388774   
min        1.000000     11.000000  2.995780e+17      0.000000     -0.004136   
25%        2.000000    184.000000  3.389248e+17      0.000000      0.000081   
50%        4.000000    299.000000  4.966580e+17      1.000000      0.042591   
75%        5.000000    414.000000  2.881300e+18      2.000000      0.092579   
max        6.000000    768.000000  9.468830e+18      2.000000      5.353854   

              plate           mjd       fiberid  
count  10000.000000  10000.000000  10000.000000  
mean    1460.986400  52943.533300    353.069400  
std     1788.778371   1511.150651    206.298149  
min      266.000000  51578.000000      1.000000  
25%      301.000000  51900.000000    186.750000  
50%      441.000000  51997.000000    351.000000  
75%     2559.000000  54468.000000    510.000000  
max     8410.000000  57481.000000   1000.000000

In [13]:
df.isnull().sum()

objid        0
ra           0
dec          0
u            0
g            0
r            0
i            0
z            0
run          0
rerun        0
camcol       0
field        0
specobjid    0
class        0
redshift     0
plate        0
mjd          0
fiberid      0
dtype: int64

In [14]:
df.skew()

objid        0.000000
ra          -1.227350
dec          1.191544
u           -1.219795
g           -0.536293
r           -0.021673
i            0.286442
z            0.214313
run          0.412555
rerun        0.000000
camcol      -0.100220
field        0.249795
specobjid    1.794627
class        0.169292
redshift     4.265729
plate        1.794609
mjd          1.039610
fiberid      0.308053
dtype: float64

In [15]:
df.corr()

objid            ra           dec             u  \
objid      1.000000e+00  2.524419e-14 -1.937483e-15  5.581214e-14   
ra         2.524419e-14  1.000000e+00  3.596046e-03  3.123756e-02   
dec       -1.937483e-15  3.596046e-03  1.000000e+00  3.527932e-02   
u          5.581214e-14  3.123756e-02  3.527932e-02  1.000000e+00   
g          1.001149e-13  4.390863e-02  6.187471e-02  8.492320e-01   
r          2.995673e-14  4.710290e-02  6.340395e-02  6.923790e-01   
i          2.212198e-14  4.573107e-02  5.829189e-02  6.026302e-01   
z         -4.107700e-14  4.294957e-02  5.687030e-02  5.514828e-01   
run       -1.553011e-14 -9.274056e-02  7.783849e-01  3.822910e-02   
rerun               NaN           NaN           NaN           NaN   
camcol     1.921887e-15 -6.293831e-03  1.146139e-01  9.944672e-03   
field      5.938881e-16  5.946996e-01 -1.314714e-01  8.547880e-03   
specobjid -1.829075e-15 -9.532711e-02  8.834533e-02 -1.294293e-01   
class     -3.355500e-15 -4.321896e-02 -5.891815e-02 -2.690437e-01   
redshift   5.085882e-16  3.030740e-02  6.702076e-02  1.637409e-01   
plate      4.156934e-16 -9.532933e-02  8.834153e-02 -1.294304e-01   
mjd       -3.317582e-15 -8.688726e-02  6.614663e-02 -1.687927e-01   
fiberid    4.665195e-15  5.748482e-02  1.550124e-01  1.130112e-02   

                      g             r             i             z  \
objid      1.001149e-13  2.995673e-14  2.212198e-14 -4.107700e-14   
ra         4.390863e-02  4.710290e-02  4.573107e-02  4.294957e-02   
dec        6.187471e-02  6.340395e-02  5.829189e-02  5.687030e-02   
u          8.492320e-01  6.923790e-01  6.026302e-01  5.514828e-01   
g          1.000000e+00  9.581062e-01  9.074187e-01  8.796222e-01   
r          9.581062e-01  1.000000e+00  9.776718e-01  9.691967e-01   
i          9.074187e-01  9.776718e-01  1.000000e+00  9.815066e-01   
z          8.796222e-01  9.691967e-01  9.815066e-01  1.000000e+00   
run        5.844630e-02  5.726060e-02  4.976478e-02  4.825225e-02   
rerun               NaN           NaN           NaN           NaN   
camcol     1.022304e-02  1.074725e-02  1.346079e-02  1.092981e-02   
field      1.465110e-02  1.713294e-02  1.978147e-02  1.824845e-02   
specobjid -5.497908e-02  1.978831e-02  7.295994e-02  1.123981e-01   
class     -9.921163e-02  4.962769e-02  1.467908e-01  2.157584e-01   
redshift   4.075763e-01  4.410797e-01  4.314500e-01  4.240342e-01   
plate     -5.498078e-02  1.978671e-02  7.295843e-02  1.123969e-01   
mjd       -9.277155e-02 -9.344506e-03  5.089616e-02  9.565845e-02   
fiberid    4.718739e-02  6.108141e-02  6.997739e-02  6.797999e-02   

                    run  rerun        camcol         field     specobjid  \
objid     -1.553011e-14    NaN  1.921887e-15  5.938881e-16 -1.829075e-15   
ra        -9.274056e-02    NaN -6.293831e-03  5.946996e-01 -9.532711e-02   
dec        7.783849e-01    NaN  1.146139e-01 -1.314714e-01  8.834533e-02   
u          3.822910e-02    NaN  9.944672e-03  8.547880e-03 -1.294293e-01   
g          5.844630e-02    NaN  1.022304e-02  1.465110e-02 -5.497908e-02   
r          5.726060e-02    NaN  1.074725e-02  1.713294e-02  1.978831e-02   
i          4.976478e-02    NaN  1.346079e-02  1.978147e-02  7.295994e-02   
z          4.825225e-02    NaN  1.092981e-02  1.824845e-02  1.123981e-01   
run        1.000000e+00    NaN  1.518143e-01 -4.638975e-01  9.360436e-02   
rerun               NaN    NaN           NaN           NaN           NaN   
camcol     1.518143e-01    NaN  1.000000e+00 -6.792055e-02  4.080943e-02   
field     -4.638975e-01    NaN -6.792055e-02  1.000000e+00 -9.372375e-02   
specobjid  9.360436e-02    NaN  4.080943e-02 -9.372375e-02  1.000000e+00   
class     -7.816172e-02    NaN -6.185920e-03  7.712555e-03  5.854925e-01   
redshift   5.905595e-02    NaN  6.833537e-03  1.541360e-02 -3.808992e-02   
plate      9.360107e-02    NaN  4.079461e-02 -9.372323e-02  1.000000e+00   
mjd        7.035433e-02    NaN  2.628396e-02 -8.655805e-02  9.668799e-01   
fiberid    1.385659e-01   

In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB

In [17]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.model_selection import train_test_split
import warnings
warnings.filterwarnings("ignore")


In [19]:
x=df.drop("class",axis=1)

In [20]:
y=df["class"]

In [21]:
from sklearn.preprocessing import StandardScaler

In [22]:
sc=StandardScaler()

In [23]:
scaled_x=sc.fit_transform(x)

In [24]:
scaled_x

array([[ 0.        ,  0.16745842, -0.58492272, ...,  1.03148936,
         1.30931064,  0.66863177],
       [ 0.        ,  0.16886159, -0.58311429, ..., -0.63621258,
        -0.87919741,  0.91101156],
       [ 0.        ,  0.17057433, -0.58347525, ..., -0.65633905,
        -0.60919097,  0.77527888],
       ...,
       [ 0.        , -0.92039468,  1.46090664, ...,  3.26608697,
         2.69309363,  1.3036668 ],
       [ 0.        , -0.92197294,  1.46432109, ..., -0.56688806,
        -0.70581092, -0.60143828],
       [ 0.        , -0.91804124,  1.46639319, ..., -0.56688806,
        -0.70581092, -0.5820479 ]])

In [25]:
x_train,x_test,y_train,y_test=train_test_split(scaled_x,y,test_size=0.30,random_state=42)

In [27]:
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((7000, 17), (3000, 17), (7000,), (3000,))

In [28]:
dtc=DecisionTreeClassifier()

In [30]:
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [31]:
pred=dtc.predict(x_test)

In [36]:
print(accuracy_score(y_test,pred))

0.9846666666666667


In [38]:
print(confusion_matrix(y_test,pred))

[[1477   17    3]
 [  20  266    0]
 [   4    2 1211]]


In [39]:
print(classification_report(y_test,pred))

              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1497
           1       0.93      0.93      0.93       286
           2       1.00      1.00      1.00      1217

    accuracy                           0.98      3000
   macro avg       0.97      0.97      0.97      3000
weighted avg       0.98      0.98      0.98      3000



In [40]:
SVC=SVC()
SVC.fit(x_train,y_train)
pred_svc=SVC.predict(x_test)

In [42]:
print(accuracy_score(y_test,pred_svc))

0.9546666666666667


In [43]:
print(confusion_matrix(y_test,pred))
print("***************************************************************")
print(classification_report(y_test,pred))

[[1477   17    3]
 [  20  266    0]
 [   4    2 1211]]
***************************************************************
              precision    recall  f1-score   support

           0       0.98      0.99      0.99      1497
           1       0.93      0.93      0.93       286
           2       1.00      1.00      1.00      1217

    accuracy                           0.98      3000
   macro avg       0.97      0.97      0.97      3000
weighted avg       0.98      0.98      0.98      3000



In [44]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
knn_pred=knn.predict(x_test)
print(accuracy_score(y_test,knn_pred))

0.893


Accuracy score is maximum in in decision tree classifier that is 98 percent hence we wil save tha model

In [45]:
import pickle
filename="space_server.pkl"
pickle.dump(dtc,open(filename,"wb"))